### ISSUE TITLE
Pre-Launch Tracker

### ISSUE THREAD

**Issue by mikkokotila** [world-federation-of-advertisers/Docs-Frontend#1]
## Must do first

- [x] Create the directory structure
- [x] Automate docs fetching
- [ ] Test docs fetch automation in different scenarios
- [x] Create Docute site structure
- [x] Add Docute to repo
- [ ] Setup Cloudflare Pages
- [ ] Setup custom domain for Cloudflare Pages
- [ ] Test Cloudflare Pages deployment
- [ ] Test through all the clickable things in the docs

## Maybe doing after

- [ ] Fail workflow gracefully in the case already up-to-date (as opposed to failing the run)
- [ ] Improve styling
